user:
  gavatar_url: "https://secure.gravatar.com/avatar/"
  default_password: "123456789"
  role:
    - normal
    - admin
    - teacher
session:
  number: "1"
category_type:
  all_word: "all_word"
  learned: "learned"
  not_learn: "not_learn"
